name: ZTC Kernel Build
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch: # This allows this workflow to be called from another workflow

jobs:
  build-kernel-kernelsu-susfs:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Maximize Build Space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'          # Frees ~2 GB
          remove-android: 'true'         # Frees ~9 GB
          remove-haskell: 'true'         # Frees ~5.2 GB
          remove-codeql: 'true'          # Frees ~5.4 GB
          remove-docker-images: 'true'   # Frees ~3.2 GB
          remove-large-packages: 'true'  # Frees ~3.1 GB
          remove-cached-tools: 'false'   # Avoid unless confirmed safe
          verbose: 'true'                # Enable detailed logging

      - name: 设定 CONFIG 环境变量
        run: |
          # Set CONFIG dynamically based on inputs values
          DIR="android12-5.10-lts"
          CONFIG="$DIR/common/arch/arm64/configs/gki_defconfig"
          # Set CONFIG as an environment variable for future steps
          echo "DIR=$DIR" >> $GITHUB_ENV
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      # Install ccache
      - name: 安装 依赖
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y ccache python3 git curl build-essential libssl-dev bison flex libelf-dev dwarves

      - name: 配置 ccache
        run: |
          mkdir -p ~/.cache/bazel
          ccache --version
          ccache --max-size=20G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
      
      - name: 安装仓库
        run: |
          # Install dependencies
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV

      - name: 克隆 AnyKernel3 和其他依赖项
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."

          ANYKERNEL_BRANCH="gki-2.0"
          SUSFS_BRANCH="gki-android12-5.10"

          # Clone repositories using the branch names
          git clone https://github.com/WildPlusKernel/AnyKernel3.git -b "$ANYKERNEL_BRANCH"

      - name: 初始化和同步内核源代码
        run: |
          echo "Creating folder for configuration: $CONFIG..."
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          # Initialize and sync kernel source
          echo "Initializing and syncing kernel source..."
          FORMATTED_BRANCH="android12-5.10-lts"
          $REPO init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-${FORMATTED_BRANCH}
          REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${FORMATTED_BRANCH})
          # Sync repo and apply patches
          sed -i '/name="kernel\/common"/d' .repo/manifests/default.xml
          $REPO --version
          $REPO --trace sync -c -j$(nproc --all)
          rm -rf common
          git clone https://github.com/ztc1997/android_gki_kernel_5.10_common.git -b android12-5.10-2025-12 --recurse-submodules --depth=1 common      
          curl -LSs "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-r584948.tar.gz" -o clang-r584948.tar.gz
          mkdir prebuilts-master/clang/host/linux-x86/clang-r584948
          tar -xzvf clang-r584948.tar.gz -C prebuilts-master/clang/host/linux-x86/clang-r584948
          # ln -s "$(pwd)/clang/clang-r584948" "$(pwd)/prebuilts-master/clang/host/linux-x86/clang-r584948"
          cd common
          sed -i 's|^CLANG_PREBUILT_BIN=.*|CLANG_PREBUILT_BIN=prebuilts-master/clang/host/linux-x86/clang-r584948/bin|' build.config.common
          
      - name: 配置内核构时间/删除dirty字符
        run: |
          cd "$DIR"
          echo "5系:删除dirty字符串"
          sed -i 's/-dirty//' ./common/scripts/setlocalversion
          
      - name: 添加ipset等功能
        run: |
            echo "更改为配置目录: $CONFIG..."
            cd "$DIR"
            echo "CONFIG_BPF_STREAM_PARSER=y" >> $CONFIG
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> $CONFIG
            echo "CONFIG_NETFILTER_XT_SET=y" >> $CONFIG
            echo "CONFIG_IP_SET=y" >> $CONFIG
            echo "CONFIG_IP_SET_MAX=65534" >> $CONFIG
            echo "CONFIG_IP_SET_BITMAP_IP=y" >> $CONFIG
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> $CONFIG
            echo "CONFIG_IP_SET_BITMAP_PORT=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IP=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IPMARK=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IPPORT=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_IPMAC=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_MAC=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_NET=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_NETNET=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_NETPORT=y" >> $CONFIG
            echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> $CONFIG
            echo "CONFIG_IP_SET_LIST_SET=y" >> $CONFIG
            echo "CONFIG_CGROUP_NET_CLASSID=y" >> $CONFIG
            echo "CONFIG_NETFILTER_XT_MATCH_CGROUP=y" >> $CONFIG
            echo "CONFIG_NET_CLS_CGROUP=y" >“ $CONFIG
            #nftables, maybe breaks kmi
            #echo "CONFIG_NF_TABLES=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_IPV4=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_IPV6=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_ARP=y" >> $CONFIG
            #echo "CONFIG_NF_FLOW_TABLE=y" >> $CONFIG
            #echo "CONFIG_NFT_NAT=y" >> $CONFIG
            #echo "CONFIG_NFT_FIB=y" >> $CONFIG
            #echo "CONFIG_NFT_FIB_INET=y" >> $CONFIG
            #echo "CONFIG_NFT_SYNPROXY=y" >> $CONFIG
            #echo "CONFIG_NFT_TPROXY=y" >> $CONFIG
            #echo "CONFIG_NFT_OSF=y" >> $CONFIG
            #echo "CONFIG_NFT_SOCKET=y" >> $CONFIG
            #echo "CONFIG_NFT_XFRM=y" >> $CONFIG
            #echo "CONFIG_NFT_HASH=y" >> $CONFIG
            #echo "CONFIG_NFT_COMPAT=y" >> $CONFIG
            #echo "CONFIG_NFT_REJECT=y" >> $CONFIG
            #echo "CONFIG_NFT_QUOTA=y" >> $CONFIG
            #echo "CONFIG_NFT_QUEUE=y" >> $CONFIG
            #echo "CONFIG_NFT_OBJREF=y" >> $CONFIG
            #echo "CONFIG_NFT_TUNNEL=y" >> $CONFIG
            #echo "CONFIG_NFT_REDIR=y" >> $CONFIG
            #echo "CONFIG_NFT_MASQ=y" >> $CONFIG
            #echo "CONFIG_NFT_LIMIT=y" >> $CONFIG
            #echo "CONFIG_NFT_CONNLIMIT=y" >> $CONFIG
            #echo "CONFIG_NFT_COUNTER=y" >> $CONFIG
            #echo "CONFIG_NFT_CT=y" >> $CONFIG
            #echo "CONFIG_NFT_FLOW_OFFLOAD=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_BRIDGE=y" >> $CONFIG
            #echo "CONFIG_NFT_NUMGEN=y" >> $CONFIG
            #echo "CONFIG_NF_DUP_NETDEV=y" >> $CONFIG
            #echo "CONFIG_NFT_DUP_NETDEV=y" >> $CONFIG
            #echo "CONFIG_NFT_FWD_NETDEV=y" >> $CONFIG
            #echo "CONFIG_NF_FLOW_TABLE_IPV4=y" >> $CONFIG
            #echo "CONFIG_NFT_FIB_IPV4=y" >> $CONFIG
            #echo "CONFIG_NFT_DUP_IPV4=y" >> $CONFIG
            #echo "CONFIG_NF_FLOW_TABLE_IPV6=y" >> $CONFIG
            #echo "CONFIG_NFT_FIB_IPV6=y" >> $CONFIG
            #echo "CONFIG_NFT_DUP_IPV6=y" >> $CONFIG     
            #echo "CONFIG_NFT_FIB_NETDEV=y" >> $CONFIG
            #echo "CONFIG_NFT_BRIDGE_META=y" >> $CONFIG
            #echo "CONFIG_NFT_BRIDGE_REJECT=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_INET=y" >> $CONFIG
            #echo "CONFIG_NF_TABLES_NETDEV=y" >> $CONFIG
            #echo "CONFIG_NF_FLOW_TABLE_INET=y" >> $CONFIG
            #echo "CONFIG_NFT_LOG=y" >> $CONFIG
            #echo "CONFIG_IP6_NF_NAT=y" >> $CONFIG
            #echo "CONFIG_IP6_NF_TARGET_REDIRECT=y" >> $CONFIG
            #echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y" >> $CONFIG
                        
      - name: Build with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 90
          max_attempts: 3
          retry_on: timeout
          command: |
            set -e
            set -x
            cd "$DIR"

            echo "Building the kernel..."
            LTO=thin KCFLAGS="-O3" BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC=clang || exit 1
            

      - name: 创建Bootimgs文件夹并复制镜像
        run: |
          mkdir bootimgs

          echo "Creating bootimgs folder and copying images..."
          cp ./$CONFIG/out/android12-5.10/dist/Image ./bootimgs
          cp ./$CONFIG/out/android12-5.10/dist/Image.lz4 ./bootimgs
          cp ./$CONFIG/out/android12-5.10/dist/Image ./
          cp ./$CONFIG/out/android12-5.10/dist/Image.lz4 ./

          # Create gzip of the Image file
          gzip -n -k -f -9 ./Image > ./Image.gz


      - name: 创建不同格式的ZIP文件
        run: |
          echo "Creating zip files for all formats..."
          cd ./AnyKernel3

          # Create and upload zip for each format
          ZIP_NAME="ZTC-AnyKernel3.zip"
          echo "Creating zip file: $ZIP_NAME..."
          mv ../Image ./Image

      - name: 上传编译资产 (仅 AK3)
        uses: actions/upload-artifact@v4
        with:
          name: ZTC-Anykernel3
          path: ./AnyKernel3/*
